 install.packages(c("devtools", "ggplot2", "TSA", "rootSolve", "markdown", "knitr", "gridExtra", "formatR", "dplyr"),lib="/home/nathan" ,repos="https://www.stats.bris.ac.uk/R/" )
 if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager",lib="/home/nathan" ,repos="https://www.stats.bris.ac.uk/R/" )
BiocManager::install("rain")
devtools::install_github("nathansam/CircadianTools")
q()
