 install.packages(c("devtools", "ggplot2", "TSA", "rootSolve", "markdown", "knitr", "gridExtra", "formatR", "dplyr""), repos="https://www.stats.bris.ac.uk/R/")
 if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("rain")
devtools::install_github("nathansam/CircadianTools")
q()
